### ISSUE TITLE
13.0 (17A5556d) Not compatible 

### ISSUE THREAD

**Issue by A-M-j** [xushuduo/Xcode-iOS-Developer-Disk-Image#12]
hi 

I was install iOS 13 (17A5556d) and trying to build my project with last Xcode version 10.3 but it's show me a reboot Device issue 

can you please upload last Developer disk image compatible with 13.0 (17A5556d)

**Comment by xushuduo** [comment]
I have updated the latest [iOS 13 (17A5565b)](https://github.com/xushuduo/Xcode-iOS-Developer-Disk-Image/releases/tag/13.0).
