### ISSUE TITLE
iOS Version 12.4 Not viable

### ISSUE THREAD

**Issue by arishanapalli** [xushuduo/Xcode-iOS-Developer-Disk-Image#14]
The DeveloperDiskImage for version iOS 12.4 is not available.
Will you please add it.

**Comment by Anonym0uz** [comment]
I create pull request #15 with 12.4 developer disk image from Xcode 10.3.

**Comment by xushuduo** [comment]
Updated the iOS 12.4 developer disk image file.
[Download](https://github.com/xushuduo/Xcode-iOS-Developer-Disk-Image/releases/tag/12.4)

**Comment by arishanapalli** [comment]
Thank you uploading Developer disk image 12.4
