### ISSUE TITLE
Need for iOS 13.1

### ISSUE THREAD

**Issue by beforeold** [xushuduo/Xcode-iOS-Developer-Disk-Image#16]
Hey bud, how can i get the disk image by myself?

**Comment by xushuduo** [comment]
[iOS 13.1 Developer Disk Image](https://github.com/xushuduo/Xcode-iOS-Developer-Disk-Image/releases/tag/13.1)

**Comment by zykyan** [comment]
iOS 13.2 Developer Disk Image
[13.2.zip](https://github.com/xushuduo/Xcode-iOS-Developer-Disk-Image/files/3743258/13.2.zip)
