### ISSUE TITLE
Please update Disk image for iOS 13.2.2

### ISSUE THREAD

**Issue by shahsaumil2001** [xushuduo/Xcode-iOS-Developer-Disk-Image#19]
I can't able to run in to my real device iOS 13.2.2 in Xcode 10.1 and 10.3

**Comment by xushuduo** [comment]
You can upgrade the Xcode version to 11.3.

[13.2.2](https://github.com/xushuduo/Xcode-iOS-Developer-Disk-Image/releases/tag/13.2)
