### ISSUE TITLE
Developer Disk Image for 14.6

### ISSUE THREAD

**Issue by Nikhil-Wagh** [xushuduo/Xcode-iOS-Developer-Disk-Image#31]
Please provide DDI for iOS 14.6

**Comment by elcharlie** [comment]
> Please provide DDI for iOS 14.6

Yes ,Please

**Comment by ClownWang-1217** [comment]
I wanna get it too!

**Comment by xfelipetavares** [comment]
Yes, i would like too!

**Comment by jgerits** [comment]
this is fixed with #32

**Comment by stanydsouzall** [comment]
Yes, I want it urgently

**Comment by jokerqxk** [comment]
I also need it urgently.

**Comment by xfelipetavares** [comment]
iOS 15... still nothing?
