### ISSUE TITLE
12.5.4 Developer Disk Image

### ISSUE THREAD

**Issue by HaKDMoDz** [xushuduo/Xcode-iOS-Developer-Disk-Image#34]
Please provide a developer disk image for ios 12.5.4 (16H50)

**Comment by mtaka-git** [comment]
I use this file. 
macos high sierra  xcode7.3  iOS 12.5.5
[12.5.zip](https://github.com/xushuduo/Xcode-iOS-Developer-Disk-Image/files/7456820/12.5.zip)
I get diskimage12.4, and I rename the folder name 12.4 to 12.5.

**Comment by HaKDMoDz** [comment]
Ok thank you mtaka-git your suggested method works.  I discovered just using 12.4 also worked for 12.5.5 without the need of renaming the folder.
