### ISSUE TITLE
device support signature is corrupted for iOS 13.0 Beta

### ISSUE THREAD

**Issue by MiladFaridnia** [xushuduo/Xcode-iOS-Developer-Disk-Image#9]
I have problem downloading DeveloperDiskImage.dmg.signature for Xcode Developer Disk Image for iOS 13.0 Beta. Could you please check it.

**Comment by xushuduo** [comment]
What is your version of Xcode? 

You may need to use Xcode 11 to debug iOS 13.0 devices.

**Comment by MiladFaridnia** [comment]
It's not related to Xcode version. I downloaded the file from other repos and it worked.

**Comment by xushuduo** [comment]
I have updated the latest [iOS 13 (17A5565b)](https://github.com/xushuduo/Xcode-iOS-Developer-Disk-Image/releases/tag/13.0).
You can update the latest file and try to debug it on your phone.
